config/routes.rb
Rails.application.routes.draw do
  resources :deposits
  devise_for :users, controllers: {registrations: 'registrations', sessions: 'sessions',
                                   passwords: 'passwords', confirmations: 'confirmations'}

  devise_scope :user do
    authenticated :user do
      root 'home#dashboard', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users, except: [:create] do
    get 'select_workers'
    post 'add_workers'
    delete 'remove_worker'
  end

  resources :workers do
    get 'offline', on: :collection
    get 'select_customers'
    post 'add_customers'
    delete 'remove_user'
  end

  resources :currencies, only: [:index, :edit, :update]
  resources :transactions, only: [:destroy, :index] do
    post 'change_status'
  end
  post 'transactions/withdraw' => 'transactions#withdraw', as: :withdraw
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  validates :name, :username, :country, :company_name, presence: true
  validate  :profit_share, if: Proc.new { |user| user.admin? }
  validates :profit_share, numericality: {less_than_or_equal_to: 100, message: "must be a percentage amount"}
  validates :net_income, numericality: {less_than_or_equal_to: 99999999999, message: "must be less than 10 Billion"}

  has_many :user_workers, dependent: :delete_all
  has_many :workers, through: :user_workers

  has_many :deposit_workers
  has_many :transactions

  default_scope { order(created_at: :desc) }
  scope :customers, -> { where(admin: false).order('id desc') }

  attr_accessor :worker_id, :action_name

  after_initialize :setup_password

  def country_name
    country_name = ISO3166::Country[country]
    country_name.translations[I18n.locale.to_s] || country_name.name
  end

  def address
    return country_name if street_name.blank?
    [street_name, country_name].join(' - ')
  end

  def add_worker(worker_id, worker_count)
    self.user_workers.create(worker_id: worker_id, worker_count: worker_count)
  end

  def worker_exists?(worker_id)
    return true if self.workers.pluck(:id).include? worker_id
    false
  end

  def validate_workers(params)
    return false, "Worker Already Selected." if self.worker_exists?(params[:worker_id].to_i)
    return false, "Please select a worker." if params[:worker_id].blank?
    return false, "Worker count can neither be blank nor 0" if params[:worker_count].blank? || params[:worker_count] == "0"
    return false, "Worker count is greater than workers left in this group." if params[:worker_count].to_i > Worker.find(params[:worker_id].to_i).remaining_worker_count
    true
  end

  def update_net_income(worker_id, income_amount, currency_code)
    worker = Worker.find(worker_id)
    calculated_net_income = income_amount * self.get_worker_count(worker_id) * (profit_share / 100)
    case currency_code
    when 'BTC'
      self.btc_net_income += calculated_net_income
    when 'LTC'
      self.ltc_net_income += calculated_net_income
    when 'BCH'
      self.bch_net_income += calculated_net_income
    end
  end

  def deduct_net_income(worker_id, income_amount, currency_code)
    worker = Worker.find(worker_id)
    calculated_net_income = income_amount * self.get_worker_count(worker_id) * (profit_share / 100)
    case currency_code
    when 'BTC'
      self.btc_net_income -= calculated_net_income
    when 'LTC'
      self.ltc_net_income -= calculated_net_income
    when 'BCH'
      self.bch_net_income -= calculated_net_income
    end
  end

  def daily_income_for_worker(worker)
    worker.get_income_for_worker_count(self.id, Deposit.net_income_for_worker_today(worker.id))
  end

  def income_today_for_workers(workers)
    daily_income = 0.0
    workers.each do |worker|
      daily_income += daily_income_for_worker(worker)
    end
    daily_income
  end

  def net_income_for_workers(workers)
    total_income = 0.0
    workers.each do |worker|
      total_income += worker.get_user_net_income(self.id)
    end
    total_income
  end

  def get_worker_count(worker_id)
    self.user_workers.for_worker(worker_id).worker_count
  end

  def update_net_income_for_currency(amount, currency_code)
    case currency_code
    when 'BTC'
      self.btc_net_income -= amount
    when 'LTC'
      self.ltc_net_income -= amount
    when 'BCH'
      self.bch_net_income -= amount
    end
  end

  def net_income_for_currency(currency_code)
    return btc_net_income if currency_code == 'BTC'
    return ltc_net_income if currency_code == 'LTC'
    bch_net_income if currency_code == 'BCH'
  end

  def pending_transactions_exist?(currency)
    curr = Currency.find_by_code(currency)
    self.transactions.exists?(currency: curr.id, status: 'pending')
  end

  private

  def setup_password
    return if self.persisted?
    self.confirmed_at = DateTime.now
    self.password = self.password_confirmation = Devise.friendly_token.first(8) unless self.admin
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :set_redirect_url, only: [:update]

  def index
    @users = User.customers.paginate(page: params[:page], per_page: Worker::PER_PAGE)
  end

  def show
    @user_workers = @user.workers.paginate(page: params[:page], per_page: Worker::PER_PAGE)
  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update(edit_user_params.except(:action_name))
        format.html { redirect_to @redirect_url, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_path, alert: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def select_workers
    @user = User.find(params[:user_id])
    @workers = Worker.all
  end

  def add_workers
    @user = User.find(params[:user_id])
    valid, message = @user.validate_workers(params)
    if valid
      @user.add_worker(params[:worker_id], params[:worker_count])
      respond_to do |format|
        format.html { redirect_to @user, notice: 'Workers were successfully added.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to user_select_workers_path, alert: message }
        format.json { head :no_content }
      end
    end
  end

  def remove_worker
    @user = User.find(params[:user_id])
    @user.user_workers.find_by_worker_id(params[:worker_id]).destroy
    respond_to do |format|
      format.html { redirect_to @user, alert: "Worker for Customer #{@user.name.titleize} was successfully removed." }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def edit_user_params
      params.require(:user).permit(:name, :company_name, :zip, :country,
                                    :street_name, :profit_share, :action_name,
                                    :btc_mining_address, :ltc_mining_address, :bch_mining_address)
    end

    def set_redirect_url
      @redirect_url = users_path
      @redirect_url = @user if edit_user_params[:action_name] == 'show'
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def get_selected_country(user)
    user.country if user.new_record?
  end

  def form_submit_text(form_object, object_type)
    form_object.persisted? ? "Update #{object_type}" : "Add #{object_type}"
  end

  def back_user_form_url(action_name, user)
    return users_path if action_name == 'index' || user.new_record?
    user if action_name == 'show' || action_name.blank?
  end

  def back_user_show_url
    return users_path if current_user.admin
    authenticated_root_path
  end

  def check_mining_addresses(user)
    str = ""
    str = "BTC" if user.btc_mining_address.present?
    str = [str, "LTC"].join(", ") if user.ltc_mining_address.present?
    str = [str, "BCH"].join(", ") if user.bch_mining_address.present?
    return "Not Found" if str.blank?
    ["<i class='fa fa-check-circle'></i>", str].join(" ").html_safe
  end
end

app/views/users/_form.html.erb
<%= form_for(user) do |form| %>
  <%= form.hidden_field :action_name, value: params[:method] if params[:method].present? %>
  <% if user.errors.any? %>
    <% user.errors.full_messages.each do |message| %>
      <div class="alert alert-danger alert-dismissable">
        <i class="fa fa-ban"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <b><%= message %></b>
      </div>
    <% end %>
  <% end %>
  <div class="box-body">
    <%= render 'users/form_fields_row1', form: form %>
    <div class="row">
      <div class="col-xs-4">
        <div class="form-group">
          <%= form.label :company_name, "Company Name" %>
          <%= form.text_field :company_name, required: true, class: "form-control", placeholder: "Enter Customer Company Name" %>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="form-group">
          <%= form.label :country %>
          <%= form.country_select :country, {prompt: "Please select a country"}, {selected: get_selected_country(form.object), class: "form-control", required: true} %>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="form-group">
          <%= form.label :zip %>
          <%= form.text_field :zip, required: true, class: "form-control", placeholder: "Enter Customer Zip Code" %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-4">
        <div class="form-group">
          <%= form.label :street_name, "Street Name" %>
          <%= form.text_field :street_name, required: true, class: "form-control", placeholder: "Enter Customer Street Name" %>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="form-group">
          <%= form.label :btc_mining_address, "BTC Mining Address" %>
          <%= form.text_field :btc_mining_address, placeholder: "Enter Customer BTC Mining Address",class: "form-control" %>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="form-group">
          <%= form.label :ltc_mining_address, "LTC Mining Address" %>
          <%= form.text_field :ltc_mining_address, placeholder: "Enter Customer LTC Mining Address",class: "form-control" %>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="form-group">
          <%= form.label :bch_mining_address, "BCH Mining Address" %>
          <%= form.text_field :bch_mining_address, placeholder: "Enter Customer BCH Mining Address",class: "form-control" %>
        </div>
      </div>
      <% if current_user.admin? %>
        <div class="col-xs-4">
          <div class="form-group">
            <%= form.label :profit_share, "Profit Share" %>
            <%= form.number_field :profit_share, placeholder: "Enter Customer Profit Share amount", required: true, step: :any, class: "form-control" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="box-footer">
    <%= form.submit form_submit_text(form.object, 'Customer'), class: "btn btn-success margin-r-5" %>
    <%= link_to 'Back', back_user_form_url(params[:method], form.object), class: "btn btn-default" %>
  </div>
<% end %>

app/views/users/_form_fields_row1.html.erb
<div class="row">
  <% if form.object.new_record? %>
    <div class="col-xs-4">
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, required: true, class: "form-control", placeholder: "Enter Name" %>
      </div>
    </div>
    <%= render 'users/new_user_fields', f: form %>
  <% else %>
    <div class="col-xs-8">
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, required: true, class: "form-control", placeholder: "Enter Name" %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/_new_user_fields.html.erb
<div class="col-xs-4">
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, required: true, class: "form-control", placeholder: "Enter Email" %>
  </div>
</div>
<div class="col-xs-4">
  <div class="form-group">
    <%= f.label :username %>
    <%= f.text_field :username, required: true, class: "form-control", placeholder: "Enter Username" %>
  </div>
</div>

app/views/users/_user_workers.html.erb
<div class="box show-box">
  <div class="box-header">
    <h3 class="box-title"><b><%= titleize(@user.name) %> Workers</b></h3>
    <% if current_user.admin %>
      <div class="box-tools pull-right">
        <%= link_to "Select Workers", user_select_workers_path(@user), class: "btn btn-sm btn-primary" %>
      </div>
    <% end %>
  </div>
  <div class="box-body">
    <% if @user_workers.any? %>
      <div class="table-responsive">
        <table class="table no-margin">
          <thead>
            <tr>
              <th>Title</th>
              <th><i class="fa fa-bolt"></i> Cost</th>
              <th>Worker Count</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @user_workers.each do |worker| %>
              <tr>
                <td><%= truncate titleize(worker.title) %></td>
                <td><i class="fa fa-euro"></i> <%= worker.electricity_cost.to_f %></td>
                <td><%= worker.user_workers.for_user(@user.id).worker_count %></td>
                <td>
                  <% if current_user.admin %>
                    <%= link_to user_remove_worker_path(user_id: @user, worker_id: worker), method: :delete, data: { confirm: "Are you sure you want to remove worker for this customer?" } do %>
                      <i class="fa fa-trash"></i>
                    <% end %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% else %>
      <%= no_data_message(@user.workers) %>
    <% end %>
  </div>
  <div class="box-footer">
    <div class="flickr_pagination">
      <%= will_paginate @user_workers, container: false %>
    </div>
  </div>
</div>

app/views/users/_user_workers_links.html.erb
<%= no_data_message(user.workers) %>
<% user.workers.each do |worker| %>
  <%= link_to truncate(titleize(worker.title)), worker_path(worker) %>
<% end %>

app/views/users/edit.html.erb
<div class="box box-success">
  <div class="box-header with-border">
    <h3 class="box-title">Edit <%= titleize(@user.name) %> Customer</h3>
  </div>
  <%= render 'form', user: @user, action_name: params[:method] %>
</div>

app/views/users/index.html.erb
<div class="box box-success">
  <div class="box-header with-border">
    <h3 class="box-title">Customers</h3>
    <div class="box-tools pull-right">
      <%= link_to "Add New Customer", new_user_path, class: "btn btn-sm btn-success" %>
    </div>
  </div>
  <div class="box-body">
    <div class="table-responsive">
      <table class="table no-margin">
        <thead>
          <tr>
            <th>Name</th>
            <th>Country</th>
            <th>Company</th>
            <th>Profit Share</th>
            <th>BTC Net Income</th>
            <th>LTC Net Income</th>
            <th>BCH Net Income</th>
            <th>Mining Addresses</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <%= no_data_message(@users) %>
          <% @users.each do |user| %>
            <tr>
              <td><%= titleize(user.name) %></td>
              <td><%= user.country_name %></td>
              <td><%= titleize(user.company_name) %></td>
              <td><%= user.profit_share %> %</td>
              <td><%= currency_symbol_code('BTC') %> <%= user.btc_net_income %></td>
              <td><%= currency_symbol_code('LTC') %> <%= user.ltc_net_income %></td>
              <td><%= currency_symbol_code('BCH') %> <%= user.bch_net_income %></td>
              <td><%= check_mining_addresses(user) %></td>
              <td>
                <%= link_to user do %>
                  <i class="fa fa-eye"></i>
                <% end %>
              </td>
              <td>
                <%= link_to edit_user_path(user, method: 'index') do %>
                  <i class="fa fa-edit"></i>
                <% end %>
              </td>
              <td>
                <% unless user.admin %>
                  <%= link_to user, method: :delete, data: { confirm: "Are you sure?" } do %>
                    <i class="fa fa-trash"></i>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="box-footer">
    <div class="flickr_pagination">
      <%= will_paginate @users, container: false %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="box box-success">
  <div class="box-header with-border">
    <h3 class="box-title">Add New Customer</h3>
  </div>
  <%= render 'form', user: @user %>
</div>

app/views/users/select_workers.html.erb
<%= form_tag user_add_workers_path, method: :post do |form| %>
  <div class="box box-success">
    <div class="box-header with-border">
      <h3 class="box-title"><%= titleize(@user.name) %></h3>
    </div>
    <div class="box-body">
      <div class="row">
        <div class="col-xs-6">
          <div class="form-group">
            <%= label_tag :worker_id, "Worker" %>
            <%= select_tag :worker_id, options_for_select(
                  @workers.map { |w| [ truncate(titleize(w.title)), w.id ] }
                ), include_blank: 'Select Worker', class: "form-control", required: true %>
          </div>
        </div>
        <div class="col-xs-6">
          <div class="form-group">
            <%= label_tag :worker_count, "Workers Count" %><br/>
            <%= number_field_tag :worker_count, "", class: "form-control", required: true %>
          </div>
        </div>
      </div>
    </div>
    <div class="box-footer">
      <%= submit_tag "Add Worker", class: "btn btn-success margin-r-5" %>
      <%= link_to 'Back', user_path(@user), class: "btn btn-default" %>
    </div>
</div>
<% end %>

app/views/users/show.html.erb
<div class="box box-success">
  <div class="box-header with-border">
    <h3 class="box-title"><%= titleize(@user.name) %></h3>
    <div class="box-tools pull-right">
      <%= link_to edit_user_path(@user, method: 'show'), class: "btn btn-box-tool show-actions" do %>
        <i class="fa fa-edit"></i>
      <% end %>
      <% if current_user.admin && not(@user.admin) %>
        <%= link_to @user, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-box-tool show-actions" do %>
          <i class="fa fa-trash"></i>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="box-body customer-show">
    <div class="row">
      <div class="col-xs-4">
        <strong><i class="fa fa-envelope margin-r-5"></i> Email</strong>
        <p class="text-muted"><%= @user.email %></p>
      </div>
      <div class="col-xs-4">
        <strong><i class="fa fa-sign-in margin-r-5"></i> Username</strong>
        <p class="text-muted"><%= @user.username %></p>
      </div>
      <div class="col-xs-4">
        <strong><i class="fa fa-map-marker margin-r-5"></i> Address</strong>
        <p class="text-muted"><%= @user.address %></p>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-xs-4">
        <strong><i class="fa fa-th margin-r-5"></i> BTC Mining Address</strong>
        <p class="text-muted"><%= @user.btc_mining_address? ? @user.btc_mining_address : "Not Found" %></p>
      </div>
      <div class="col-xs-4">
        <strong><i class="fa fa-th margin-r-5"></i> LTC Mining Address</strong>
        <p class="text-muted"><%= @user.ltc_mining_address? ? @user.ltc_mining_address : "Not Found" %></p>
      </div>
      <div class="col-xs-4">
        <strong><i class="fa fa-th margin-r-5"></i> BCH Mining Address</strong>
        <p class="text-muted"><%= @user.bch_mining_address? ? @user.bch_mining_address : "Not Found" %></p>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-xs-4">
        <strong><i class="fa fa-credit-card-alt margin-r-5"></i> BTC Net Income</strong>
        <p class="text-muted"><%= currency_symbol_code('BTC') %> <%= @user.btc_net_income %></p>
      </div>
      <div class="col-xs-4">
        <strong><i class="fa fa-credit-card-alt margin-r-5"></i> LTC Net Income</strong>
        <p class="text-muted"><%= currency_symbol_code('LTC') %> <%= @user.ltc_net_income %></p>
      </div>
      <div class="col-xs-4">
        <strong><i class="fa fa-credit-card-alt margin-r-5"></i> BCH Net Income</strong>
        <p class="text-muted"><%= currency_symbol_code('BCH') %> <%= @user.bch_net_income %></p>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-xs-4">
        <strong><i class="fa fa-building margin-r-5"></i> Company</strong>
        <p class="text-muted"><%= @user.company_name %></p>
      </div>
      <div class="col-xs-4">
        <strong><i class="fa fa-percent margin-r-5"></i> Profit Share</strong>
        <p class="text-muted"><%= @user.profit_share %> %</p>
      </div>
    </div>
  </div>

  <%= render partial: "users/user_workers" %>

  <div class="box-footer clearfix">
    <%= link_to "Back", back_user_show_url, class: "btn btn-default" %>
  </div>
</div>