config/routes.rb
Rails.application.routes.draw do
  resources :deposits
  devise_for :users, controllers: {registrations: 'registrations', sessions: 'sessions',
                                   passwords: 'passwords', confirmations: 'confirmations'}

  devise_scope :user do
    authenticated :user do
      root 'home#dashboard', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users, except: [:create] do
    get 'select_workers'
    post 'add_workers'
    delete 'remove_worker'
  end

  resources :workers do
    get 'offline', on: :collection
    get 'select_customers'
    post 'add_customers'
    delete 'remove_user'
  end

  resources :currencies, only: [:index, :edit, :update]
  resources :transactions, only: [:destroy, :index] do
    post 'change_status'
  end
  post 'transactions/withdraw' => 'transactions#withdraw', as: :withdraw
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def dashboard
    if current_user.admin
      @workers_count = Worker.all.count
      @customers_count = User.all.count
      @offline_workers = Worker.offline
      @latest_deposits = Deposit.latest
      @chart_data = @latest_deposits.group_by(&:date)
      @daily_deposits = @latest_deposits.group_by { |d| [d.date, d.worker] }
    else
      @customer_workers = Worker.get_customer_workers(current_user)
      @litecoin_workers = @customer_workers.get_currency_workers('LTC')
      @litecoin_income_today = current_user.income_today_for_workers(@litecoin_workers)
      @litecoin_workers_count = @litecoin_workers.exists? ? @litecoin_workers.sum(:worker_count) : 0
      @litecoin_net_income = current_user.ltc_net_income

      @bitcoin_workers = @customer_workers.get_currency_workers('BTC')
      @bitcoin_income_today = current_user.income_today_for_workers(@bitcoin_workers)
      @bitcoin_workers_count = @bitcoin_workers.exists? ? @bitcoin_workers.sum(:worker_count) : 0
      @bitcoin_net_income = current_user.btc_net_income

      @bitcash_workers = @customer_workers.get_currency_workers('BCH')
      @bitcash_income_today = current_user.income_today_for_workers(@bitcash_workers)
      @bitcash_workers_count = @bitcash_workers.exists? ? @bitcash_workers.sum(:worker_count) : 0
      @bitcash_net_income = current_user.bch_net_income
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def to_euro(amount, currency)
    return btc_to_euro(amount) if currency == 'BTC'
    return ltc_to_euro(amount) if currency == 'LTC'
    bch_to_euro(amount) if currency == 'BCH'
  end

  def btc_to_euro(amount)
    round_income(amount * Currency.bitcoin_rate, 8)
  end

  def ltc_to_euro(amount)
    round_income(amount * Currency.litcoin_rate, 8)
  end

  def bch_to_euro(amount)
    round_income(amount * Currency.bitcash_rate, 8)
  end

  def round_income(income, decimal)
    "%.#{decimal}f" % income
  end

  def currency_icon_box(currency)
    return image_tag("LTC-icon.png", class: "ltc-icon custom-icon box-icon", alt: "Litcoin") if currency == 'LTC'
    return image_tag("BCH-icon.png", class: "bch-icon custom-icon box-icon", alt: "Bitcoin Cash") if currency == 'BCH'
    "<div class='icon'><i class='ion ion-social-bitcoin'></i></div>".html_safe if currency == 'BTC'
  end

  def currency_icon_balance(currency)
    return image_tag("LTC-icon.png", class: "ltc-icon custom-icon", alt: "Litcoin") if currency == 'LTC'
    return image_tag("BCH-icon.png", class: "bch-icon custom-icon", alt: "Bitcoin Cash") if currency == 'BCH'
    "<i class='ion ion-social-bitcoin'></i>".html_safe if currency == 'BTC'
  end

  def show_respective_mining_address_for_code(user, code)
    return user.btc_mining_address? ? user.btc_mining_address : "Not Found" if code == 'BTC'
    return user.ltc_mining_address? ? user.ltc_mining_address : "Not Found" if code == 'LTC'
    user.bch_mining_address? ? user.bch_mining_address : "Not Found" if code == 'BCH'
  end
end

app/views/home/_admin_dashboard.html.erb
<div class="row">
  <div class="col-lg-4 col-xs-6">
    <div class="small-box bg-yellow">
      <div class="inner">
        <h3><%= @workers_count %></h3>

        <p>Total Workers</p>
      </div>
      <div class="icon">
        <i class="ion ion-ios-monitor-outline"></i>
      </div>
      <%= link_to workers_path, class: "small-box-footer" do %>See all Workers <i class="fa fa-arrow-circle-right"></i><% end %>
    </div>
  </div>

  <div class="col-lg-4 col-xs-6">
    <div class="small-box bg-green">
      <div class="inner">
        <h3><%= @offline_workers.count %><sup style="font-size: 20px"></sup></h3>

        <p>Offline Workers</p>
      </div>
      <div class="icon">
        <i class="ion ion-ios-monitor"></i>
      </div>
      <%= link_to offline_workers_path, class: "small-box-footer" do %>See all Offline Workers <i class="fa fa-arrow-circle-right"></i><% end %>
    </div>
  </div>

  <div class="col-lg-4 col-xs-6">
    <div class="small-box bg-yellow">
      <div class="inner">
        <h3><%= @customers_count %></h3>

        <p>Total Customers</p>
      </div>
      <div class="icon">
        <i class="icon ion-person-stalker"></i>
      </div>
      <%= link_to users_path, class: "small-box-footer" do %>See all Customers <i class="fa fa-arrow-circle-right"></i><% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-6 col-xs-12">
    <div class="box box-warning">
      <div class="box-header with-border">
        <h3 class="box-title">Latest Deposits</h3>
      </div>
      <div class="box-body">
        <div class="table-responsive">
          <table class="table no-margin">
            <thead>
            <tr>
              <th>Date</th>
              <th>Worker</th>
              <th>Income</th>
            </tr>
            </thead>
            <tbody>
            <% @latest_deposits.each do |deposit| %>
              <tr>
                <td><%= deposit.created_at.to_datetime.strftime('%d-%m-%Y') %></td>
                <td><%= link_to truncate(titleize(deposit.worker.title)), deposit.worker %></td>
                <td><%= currency_symbol(deposit.worker.currency) %> <%= deposit.income %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  <div class="col-lg-6 col-xs-12">
    <div class="box box-warning">
      <div class="box-header with-border">
        <h3 class="box-title">Daily Income/Cost</h3>
      </div>
      <div class="box-body">
        <div class="table-responsive">
          <table class="table no-margin">
            <thead>
            <tr>
              <th>Date</th>
              <th>Worker</th>
              <th>Income</th>
              <th>Cost</th>
            </tr>
            </thead>
            <tbody>
            <% @daily_deposits.each do |keys, deposits| %>
              <tr>
                <td><%= keys[0].to_datetime.strftime('%d-%m-%Y') %></td>
                <td><%= truncate titleize(keys[1].title) %></td>
                <td><%= currency_symbol(keys[1].currency) %> <%= deposits.map(&:income).sum %></td>
                <td><i class="fa fa-euro"></i> <%= keys[1].get_electricity_cost(deposits.count) %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  <div class="col-lg-12 col-xs-12">
    <div class="box box-warning">
      <div class="box-header with-border">
        <h3 class="box-title">Line Chart</h3>
      </div>
      <div class="box-body">
        <div class="chart">
          <%= content_tag :div, id: "deposits_information", data: { latest_deposits: @chart_data.values.collect {|x| x.sum(&:income)}, labels: @chart_data.keys } do %>
          <% end %>
          <canvas id="lineChart" style="height: 249px; width: 468px;" width="468" height="249"></canvas>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/_currency_workers.html.erb
<div class="row">
  <div class="col-lg-4 col-xs-6">
    <div class="small-box bg-yellow">
      <div class="inner">
        <h3><%= local_assigns[:workers] %></h3>

        <p>Total Workers</p>
      </div>
      <div class="icon">
        <i class="ion ion-ios-monitor-outline"></i>
      </div>
      <%= link_to workers_path, class: "small-box-footer" do %>See all Workers <i class="fa fa-arrow-circle-right"></i><% end %>
    </div>
  </div>

  <div class="col-lg-4 col-xs-6">
    <div class="small-box bg-yellow">
      <div class="inner">
        <h3><%= round_income(local_assigns[:income_today], 10) %></h3>

        <p><span class="text-muted"><i class="fa fa-euro"></i></span><%= to_euro(local_assigns[:income_today], local_assigns[:currency]) %> <span class="text-muted">/ Day</span></p>
      </div>

      <%= currency_icon_box(local_assigns[:currency]) %>

      <%= link_to current_user, class: "small-box-footer" do %>See Profile <i class="fa fa-arrow-circle-right"></i><% end %>
    </div>
  </div>

  <div class="col-lg-4 col-xs-12">
    <div class="box box-success">
      <div class="box-header with-border">
        <h3 class="box-title">Current Balance</h3>
      </div>
      <div class="box-body">
        <h3 class="margin-t-10">
          <div class="row">
            <div class="col-lg-12 col-xs-8">
              <span>
                <%= currency_icon_balance(local_assigns[:currency]) %>
                <%= round_income(total_balance, 10) %>
              </span>
            </div>
            <div class="col-lg-12 col-xs-4">
              <small> <span class="text-muted"><i class="fa fa-euro"></i> <%= to_euro(total_balance, local_assigns[:currency]) %></span></small>
            </div>
          </div>
        </h3>
        <hr>
        <p>Your Mining and BTC Deposit Address</p>
        <div class="font-bold"><%= show_respective_mining_address_for_code(current_user, local_assigns[:currency]) %></div>
      </div>
    </div>
  </div>
</div>

app/views/home/_customer_dashboard.html.erb
<%= render partial: 'currency_workers', locals: {
                                                  workers: @litecoin_workers_count,
                                                  currency: 'LTC',
                                                  income_today: @litecoin_income_today,
                                                  total_balance: @litecoin_net_income
                                                } if @litecoin_workers %>

<%= render partial: 'currency_workers', locals: {
                                                  workers: @bitcoin_workers_count,
                                                  currency: 'BTC',
                                                  income_today: @bitcoin_income_today,
                                                  total_balance: @bitcoin_net_income
                                                } if @bitcoin_workers %>

<%= render partial: 'currency_workers', locals: {
                                                  workers: @bitcash_workers_count,
                                                  currency: 'BCH',
                                                  income_today: @bitcash_income_today,
                                                  total_balance: @bitcash_net_income
                                                } if @bitcash_workers %>

app/views/home/dashboard.html.erb
<% if current_user.admin %>
  <%= render partial: 'admin_dashboard' %>
<% else %>
  <%= render partial: 'customer_dashboard' %>
<% end %>