config/routes.rb
Rails.application.routes.draw do
  resources :deposits
  devise_for :users, controllers: {registrations: 'registrations', sessions: 'sessions',
                                   passwords: 'passwords', confirmations: 'confirmations'}

  devise_scope :user do
    authenticated :user do
      root 'home#dashboard', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users, except: [:create] do
    get 'select_workers'
    post 'add_workers'
    delete 'remove_worker'
  end

  resources :workers do
    get 'offline', on: :collection
    get 'select_customers'
    post 'add_customers'
    delete 'remove_user'
  end

  resources :currencies, only: [:index, :edit, :update]
  resources :transactions, only: [:destroy, :index] do
    post 'change_status'
  end
  post 'transactions/withdraw' => 'transactions#withdraw', as: :withdraw
end

app/models/worker.rb
class Worker < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :electricity_cost, presence: true, numericality: {less_than: 10000}

  has_many :user_workers, dependent: :delete_all
  has_many :users, through: :user_workers

  has_many :deposits
  belongs_to :currency

  PER_PAGE = 10

  attr_accessor :user_id, :action_name

  default_scope { order(created_at: :desc) }
  scope :active, -> { left_outer_joins(:user_workers).where.not(user_workers: { user_id: nil }).uniq }
  scope :offline, -> { left_outer_joins(:user_workers).where(user_workers: { user_id: nil }) }
  scope :get_customer_workers, ->(user_id) { left_outer_joins(:user_workers).where(user_workers: { user_id: user_id }) }
  scope :get_currency_workers, -> (currency_code) { joins(:currency).where(currencies: { code: currency_code }) }

  def add_customer(user_id, worker_count)
    if self.user_exists?(user_id)
      self.user_workers.find_by_user_id(user_id).update_attributes(worker_count: worker_count)
    else
      self.user_workers.create(user_id: user_id, worker_count: worker_count)
    end
  end

  def user_exists?(user_id)
    return true if self.users.pluck(:id).include? user_id
    false
  end

  def remaining_worker_count
    self.total_workers - self.workers_in_use
  end

  def workers_in_use
    return 0 unless self.user_workers.present?
    self.user_workers.map(&:worker_count).sum
  end

  def validate_customers(params)
    return false, "Please select a customer." if params[:user_id].blank?
    return false, "Worker count can neither be blank nor 0" if params[:worker_count].blank? || params[:worker_count] == "0"
    return false, "Worker count is greater than workers left in this group." if params[:worker_count].to_i > self.remaining_worker_count
    true
  end

  def get_income_for_worker_count(user_id, income)
    self.get_customer_workers_count(user_id) * income
  end

  def get_electricity_cost(number_of_deposits)
    self.electricity_cost * number_of_deposits
  end

  def calculate_income(income, btc_price)
    income - (self.electricity_cost / btc_price)
  end

  def get_customer_workers_count(user_id)
    self.user_workers.for_user(user_id).worker_count
  end

  def get_user_net_income(user_id)
    sum_income = 0.0
    self.deposits.each do |deposit|
      sum_income += deposit.user_net_income(user_id)
    end
    sum_income
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  load_and_authorize_resource

  before_action :set_worker, only: [:show, :edit, :update, :destroy]
  before_action :set_redirect_url, only: [:update]
  before_action :set_currencies, only: [:new, :edit, :create, :update]

  def index
    @workers = current_user.admin ? Worker.all : Worker.get_customer_workers(current_user)
    @workers = @workers.paginate(page: params[:page], per_page: Worker::PER_PAGE)
  end

  def offline
    @workers = Worker.offline.paginate(page: params[:page], per_page: Worker::PER_PAGE)
    respond_to do |format|
      format.html { render 'workers/index' }
    end
  end

  def show
    @worker_users = @worker.users.paginate(page: params[:page], per_page: Worker::PER_PAGE)
    @deposits = @worker.deposits.order_by_date.paginate(page: params[:page], per_page: Worker::PER_PAGE)
  end

  def new
    @worker = Worker.new
  end

  def edit
  end

  def create
    @worker = Worker.new(worker_params)

    respond_to do |format|
      if @worker.save
        format.html { redirect_to @worker, notice: 'Worker was successfully created.' }
        format.json { render :show, status: :created, location: @worker }
      else
        format.html { render :new }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @worker.update(worker_params.except(:action_name))
        format.html { redirect_to @redirect_url, notice: 'Worker was successfully updated.' }
        format.json { render :show, status: :ok, location: @worker }
      else
        format.html { render :edit }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @worker.destroy
    respond_to do |format|
      format.html { redirect_to workers_url, alert: 'Worker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def select_customers
    @worker = Worker.find(params[:worker_id])
    @users = User.customers
  end

  def add_customers
    @worker = Worker.find(params[:worker_id])
    valid, message = @worker.validate_customers(params)
    if valid
      @worker.add_customer(params[:user_id].to_i, params[:worker_count])
      respond_to do |format|
        format.html { redirect_to @worker, notice: 'Customers were successfully added.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to worker_select_customers_path, alert: message }
        format.json { head :no_content }
      end
    end
  end

  def remove_user
    @worker = Worker.find(params[:worker_id])
    @worker.user_workers.find_by_user_id(params[:user_id]).destroy
    respond_to do |format|
      format.html { redirect_to @worker,
                    alert: "Customer for Worker #{@worker.title.titleize} was successfully removed." }
      format.json { head :no_content }
    end
  end

  private
    def set_worker
      @worker = Worker.find(params[:id])
    end

    def worker_params
      params.require(:worker).permit(:title, :description, :electricity_cost,
                                      :action_name, :total_workers, :currency_id)
    end

    def set_redirect_url
      @redirect_url = workers_path
      @redirect_url = @worker if worker_params[:action_name] == 'show'
    end

    def set_currencies
      @currencies = Currency.pluck(:code, :id)
    end
end

app/helpers/workers_helper.rb
module WorkersHelper
  def back_worker_form_url(action_name, worker)
    return workers_path if action_name == 'index' || worker.new_record?
    worker_path(worker) if action_name == 'show' || action_name.blank?
  end

  def show_worker_count(deposit, worker)
    [current_user.admin? ? worker.total_workers : deposit.get_user_worker_count(current_user.id),
      worker.title].join(' x ')
  end

  def get_selected_currency(worker)
    [worker.currency.try(:id), worker.currency.try(:name)] if worker.persisted?
  end
end

app/views/workers/_form.html.erb
<%= form_with(model: worker, local: true) do |form| %>
  <%= form.hidden_field :action_name, value: params[:method] if params[:method].present? %>
  <% if worker.errors.any? %>
    <% worker.errors.full_messages.each do |message| %>
      <div class="alert alert-danger alert-dismissable">
        <i class="fa fa-ban"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <b><%= message %></b>
      </div>
    <% end %>
  <% end %>
  <div class="box-body">
    <div class="row">
      <div class="col-xs-6">
        <div class="form-group">
          <%= form.label :title %>
          <%= form.text_field :title, required: true, class: "form-control", placeholder: "Enter Worker Group Title" %>
        </div>
      </div>
      <div class="col-xs-6">
        <div class="form-group">
          <%= form.label :description %>
          <%= form.text_area :description, class: "form-control", placeholder: "Enter Worker Group Description" %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-4">
        <div class="form-group">
          <%= form.label :electricity_cost, "Electricity Cost" %>
          <%= form.number_field :electricity_cost, required: true, placeholder: "Enter Worker Group Elictricity Cost", step: :any, class: "form-control" %>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="form-group">
          <%= form.label :total_workers, "Total Workers" %>
          <%= form.number_field :total_workers, required: true, placeholder: "Enter Total Workers in Worker Group", step: :any, class: "form-control" %>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="form-group">
          <%= form.label :currency_id, "Select Currency" %>
          <%= form.select :currency_id, options_for_select(@currencies, selected: get_selected_currency(form.object)), { include_blank: 'Please Choose' }, { class: "form-control", required: true } %>
        </div>
      </div>
    </div>
  </div>
  <div class="box-footer">
    <%= form.submit form_submit_text(form.object, "Worker Group"), class: "btn btn-success margin-r-5" %>
    <%= link_to 'Back', back_worker_form_url(params[:method], form.object), class: "btn btn-default" %>
  </div>
<% end %>

app/views/workers/_worker_users.html.erb
 <% if current_user.admin? %>
   <div class="box show-box">
    <div class="box-header with-border">
      <h3 class="box-title"><b><%= truncate titleize(@worker.title) %> Customers</b></h3>
      <% if current_user.admin %>
        <div class="box-tools pull-right">
          <%= link_to "Select Customers", worker_select_customers_path(@worker), class: "btn btn-sm btn-primary" %>
        </div>
      <% end %>
    </div>
    <div class="box-body">
      <% if @worker_users.any? %>
        <div class="table-responsive">
          <table class="table no-margin">
            <thead>
              <tr>
                <th>Name</th>
                <th>Country</th>
                <th>Company</th>
                <th>Worker Count</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @worker_users.each do |user| %>
                <tr>
                  <td><%= titleize(user.name) %></td>
                  <td><%= user.country_name %></td>
                  <td><%= titleize(user.company_name) %></td>
                  <td><%= user.user_workers.for_worker(@worker.id).worker_count %></td>
                  <td>
                    <% if current_user.admin && !(user.admin) %>
                      <%= link_to  worker_remove_user_path(user_id: user, worker_id: @worker), method: :delete, data: { confirm: "Are you sure you want to remove customer for this worker?" } do %>
                        <i class="fa fa-trash"></i>
                      <% end %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% else %>
        <%= no_data_message(@worker_users) %>
      <% end %>
    </div>
    <div class="box-footer">
      <div class="flickr_pagination">
        <%= will_paginate @worker_users, container: false %>
      </div>
    </div>
  </div>
<% end %>

<div class="box show-box">
  <div class="box-header with-border">
    <h3 class="box-title"><b><%= truncate titleize(@worker.title) %> Deposits</b></h3>
    <% if current_user.admin %>
      <div class="box-tools pull-right">
        <%= link_to "All Deposits", deposits_path, class: "btn btn-sm btn-primary" %>
      </div>
    <% end %>
  </div>
  <div class="box-body">
    <% if @deposits.any? %>
      <div class="table-responsive">
        <table class="table no-margin">
          <thead>
            <tr>
              <th>Date</th>
              <th>Exchange Rate</th>
              <th>Deposit Income</th>
              <th>Workers</th>
              <% unless current_user.admin? %>
                <th>Your Income</th>
              <% end %>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @deposits.each do |deposit| %>
              <tr>
                <td><%= deposit.date.strftime("%d-%m-%Y") %></td>
                <td><%= deposit.exchange_rate %></td>
                <td><%= currency_symbol(@worker.currency) %> <%= deposit.income %></td>
                <td><%= show_worker_count(deposit, @worker) %></td>
                <% unless current_user.admin? %>
                  <td><%= currency_symbol(@worker.currency) %> <%= deposit.income * @worker.user_workers.for_user(current_user.id).worker_count %></td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% else %>
      <%= no_data_message(@deposits) %>
    <% end %>
  </div>
  <div class="box-footer">
    <div class="flickr_pagination">
      <%= will_paginate @deposits, container: false %>
    </div>
  </div>
</div>

app/views/workers/_worker_users_links.html.erb
<%= no_data_message(worker.users) %>
<% worker.users.each do |user| %>
  <%= link_to titleize(user.name), user_path(user) %>
<% end %>

app/views/workers/edit.html.erb
<div class="box box-success">
  <div class="box-header with-border">
    <h3 class="box-title">Edit <%= titleize(@worker.title) %> Worker</h3>
  </div>
  <%= render 'form', worker: @worker %>
</div>

app/views/workers/index.html.erb
<div class="box box-success">
  <div class="box-header with-border">
    <h3 class="box-title">Worker Groups</h3>
    <% if current_user.admin %>
      <div class="box-tools pull-right">
        <%= link_to "Add New Worker", new_worker_path, class: "btn btn-sm btn-success" %>
      </div>
    <% end %>
  </div>
  <div class="box-body">
    <div class="table-responsive">
      <table class="table no-margin">
        <thead>
          <tr>
            <th>Title</th>
            <th>Description</th>
            <th><i class="fa fa-bolt"></i> Cost</th>
            <th>Currency</th>
            <% if current_user.admin? %>
              <th>Net Income</th>
              <th>Total Workers</th>
              <th>Workers In Use</th>
            <% else %>
              <th>Your Income</th>
              <th>Your Workers</th>
            <% end %>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <%= no_data_message(@workers) %>
          <% @workers.each do |worker| %>
            <tr>
              <td><%= truncate titleize(worker.title) %></td>
              <td><%= truncate worker.description %></td>
              <td><i class="fa fa-euro"></i> <%= worker.electricity_cost.to_f %></td>
              <td><%= worker.currency.try(:code) %></td>
              <td><%= currency_symbol(worker.currency) %>
                <% if current_user.admin? %>
                  <%= worker.net_income %>
                <% else %>
                  <%= worker.get_user_net_income(current_user.id) %>
                <% end %>
              </td>
              <% if current_user.admin? %>
                <td><%= worker.total_workers %></td>
                <td><%= worker.workers_in_use %></td>
              <% else %>
                <td><%= worker.get_customer_workers_count(current_user.id) %></td>
              <% end %>
              <td>
                <%= link_to worker do %>
                  <i class="fa fa-eye"></i>
                <% end %>
              </td>
              <% if current_user.admin %>
                <td>
                  <%= link_to edit_worker_path(worker, method: 'index') do %>
                    <i class="fa fa-edit"></i>
                  <% end %>
                </td>
                <td>
                  <% if current_user.admin %>
                    <%= link_to  worker, method: :delete, data: { confirm: "Are you sure?" } do %>
                      <i class="fa fa-trash"></i>
                    <% end %>
                  <% end %>
                </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="box-footer">
    <div class="flickr_pagination">
      <%= will_paginate @workers, container: false %>
    </div>
  </div>
</div>

app/views/workers/new.html.erb
<div class="box box-success">
  <div class="box-header with-border">
    <h3 class="box-title">Add New Worker</h3>
  </div>
  <%= render 'form', worker: @worker %>
</div>

app/views/workers/select_customers.html.erb
<%= form_tag worker_add_customers_path, method: :post do |form| %>
  <div class="box box-success">
    <div class="box-header with-border">
      <h3 class="box-title"><%= truncate titleize(@worker.title) %></h3>
    </div>
    <div class="box-body">
      <div class="row">
        <div class="col-xs-6">
          <div class="form-group">
            <%= label_tag :user_id, "Customer" %>
            <%= select_tag :user_id, options_for_select(
                  @users.map { |u| [titleize(u.name), u.id] }
                ), include_blank: 'Select Customer', class: "form-control", required: true %>
          </div>
        </div>
        <div class="col-xs-6">
          <div class="form-group">
            <%= label_tag :worker_count, "Workers Count" %><br/>
            <%= number_field_tag :worker_count, "", class: "form-control", required: true %>
          </div>
        </div>
      </div>
    </div>
    <div class="box-footer">
      <%= submit_tag "Add Customer", class: "btn btn-success margin-r-5" %>
      <%= link_to 'Back', worker_path(@worker), class: "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/workers/show.html.erb
<div class="box box-success">
  <div class="box-header with-border">
    <h3 class="box-title"><%= truncate titleize(@worker.title) %></h3>
    <div class="box-tools pull-right">
      <%= link_to edit_worker_path(@worker, method: 'show'), class: "btn btn-box-tool show-actions" do %>
        <i class="fa fa-edit"></i>
      <% end %>
      <% if current_user.admin %>
        <%= link_to  @worker, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-box-tool show-actions" do %>
          <i class="fa fa-trash"></i>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="box-body customer-show">
    <div class="row">
      <div class="col-xs-4">
        <strong><i class="fa fa-align-left margin-r-5"></i> Description</strong>
        <p class="text-muted"><%= @worker.description %></p>
      </div>
      <div class="col-xs-4">
        <strong><i class="fa fa-desktop margin-r-5"></i>
          <% if current_user.admin? %>
            Total Workers
          <% else %>
            Your Workers
          <% end %>
        </strong>
        <p class="text-muted">
          <% if current_user.admin? %>
             <%= @worker.total_workers %>
          <% else %>
            <%= @worker.user_workers.for_user(current_user.id).worker_count %>
          <% end %>
        </p>
      </div>
      <div class="col-xs-4">
        <strong><i class="fa fa-money margin-r-5"></i> Currency</strong>
        <p class="text-muted"><%= @worker.currency.try(:name) %></p>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-xs-4">
        <strong><i class="fa fa-bolt margin-r-5"></i> Electricity Cost</strong>
        <p class="text-muted"><i class="fa fa-euro"></i> <%= @worker.electricity_cost %></p>
      </div>
      <div class="col-xs-4">

        <strong><i class="fa fa-credit-card-alt margin-r-5"></i>
          <% if current_user.admin? %>
            Net Income
          <% else %>
            Your Net Income
          <% end %>
        </strong>
        <p class="text-muted"><%= currency_symbol(@worker.currency) %>
          <% if current_user.admin? %>
            <%= @worker.net_income %>
          <% else %>
            <%= @worker.get_user_net_income(current_user.id) %>
          <% end %>
        </p>
      </div>
    </div>
  </div>

  <%= render partial: "workers/worker_users" %>

  <div class="box-footer clearfix">
    <%= link_to "Back", workers_path, class: "btn btn-default" %>
  </div>
</div>