config/routes.rb
Rails.application.routes.draw do
  resources :deposits
  devise_for :users, controllers: {registrations: 'registrations', sessions: 'sessions',
                                   passwords: 'passwords', confirmations: 'confirmations'}

  devise_scope :user do
    authenticated :user do
      root 'home#dashboard', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users, except: [:create] do
    get 'select_workers'
    post 'add_workers'
    delete 'remove_worker'
  end

  resources :workers do
    get 'offline', on: :collection
    get 'select_customers'
    post 'add_customers'
    delete 'remove_user'
  end

  resources :currencies, only: [:index, :edit, :update]
  resources :transactions, only: [:destroy, :index] do
    post 'change_status'
  end
  post 'transactions/withdraw' => 'transactions#withdraw', as: :withdraw
end

app/views/layouts/_admin_lte_2_control_sidebar.html.erb
<aside class="control-sidebar control-sidebar-dark">
  <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
    <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab" aria-expanded="true"><i class="fa fa-home"></i></a></li>
    <li class=""><a href="#control-sidebar-settings-tab" data-toggle="tab" aria-expanded="false"><i class="fa fa-gears"></i></a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="control-sidebar-home-tab">
      <h3 class="control-sidebar-heading">Recent Activity</h3>
      <ul class="control-sidebar-menu">
        <li>
          <a href="javascript::;">
            <i class="menu-icon fa fa-birthday-cake bg-red"></i>
            <div class="menu-info">
              <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>
              <p>Will be 23 on April 24th</p>
            </div>
          </a>
        </li>
      </ul>

      <h3 class="control-sidebar-heading">Tasks Progress</h3>
      <ul class="control-sidebar-menu">
        <li>
          <a href="javascript::;">
            <h4 class="control-sidebar-subheading">
              Custom Template Design
              <span class="label label-danger pull-right">70%</span>
            </h4>
            <div class="progress progress-xxs">
              <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
            </div>
          </a>
        </li>
      </ul>
    </div>

    <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>

    <div class="tab-pane" id="control-sidebar-settings-tab">
      <form method="post">
        <h3 class="control-sidebar-heading">General Settings</h3>
        <div class="form-group">
          <label class="control-sidebar-subheading">
            Report panel usage
            <input type="checkbox" class="pull-right" checked="">
          </label>
          <p>
            Some information about this general settings option
          </p>
        </div>
      </form>
    </div>
  </div>
</aside>

app/views/layouts/_admin_lte_2_header.html.erb
<header class="main-header">

  <%= link_to "#", class: "logo" do %>
    <span class="logo-mini"><b>P</b>AP</span>
    <span class="logo-lg"><b>Philtrick</b> Admin Panel</span>
  <% end %>

  <nav class="navbar navbar-static-top" role="navigation">
    <%= link_to "#", class: "sidebar-toggle", role: "button", data: {toggle: "offcanvas"} do %>
      <span class="sr-only">Toggle navigation</span>
    <% end %>
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li class="dropdown user user-menu">
          <%= link_to "#", class: "dropdown-toggle", data: {toggle: "dropdown"} do %>
            <%= image_tag "bitcoin-logo.png", class: "user-image", alt: "User Image" %>
            <span class="hidden-xs"><%= titleize(current_user.name) %></span>
          <% end %>
          <ul class="dropdown-menu">
            <li class="user-header">
              <%= image_tag "bitcoin-logo.png", class: "img-circle", alt: "User Image" %>
              <p>
                <%= titleize(current_user.name) %> - <%= titleize(current_user.company_name) %>
                <small>Profit Share: <%= current_user.profit_share %> %</small>
              </p>
            </li>
            <li class="user-footer">
              <div class="pull-left">
                <%= link_to "Profile", user_path(current_user), class: "btn btn-default btn-flat" %>
              </div>
              <div class="pull-right">
                <%= link_to "Sign out", destroy_user_session_path, class: "btn btn-default btn-flat" %>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_admin_lte_2_sidebar.html.erb
<aside class="main-sidebar">
  <section class="sidebar">
    <div class="user-panel">
      <div class="pull-left image">
        <%= image_tag "bitcoin-logo.png", class: "img-circle", alt: "User Image" %>
      </div>
      <div class="pull-left info">
        <p><%= titleize(current_user.name) %></p>
        <%= link_to "#" do %>
          <i class="fa fa-circle text-success"></i> Online
        <% end %>
      </div>
    </div>
    <ul class="sidebar-menu">
      <li class="header">Site Links</li>
      <li class="<%= sidebar_active_class('dashboard') %>">
        <%= link_to authenticated_root_path do %>
          <i class="fa fa-dashboard"></i> <span>Dashboard</span>
        <% end %>
      </li>
      <% if can? :manage, User %>
        <li class="<%= sidebar_active_class('/users') %>">
          <%= link_to users_path do %>
            <i class="fa fa-user"></i> <span>Customers</span>
          <% end %>
        </li>
      <% end %>
      <li class="<%= sidebar_active_class('/workers') %>">
        <%= link_to workers_path do %>
          <i class="fa fa-desktop"></i> <span>Workers</span>
        <% end %>
      </li>
      <% if can? :manage, Deposit %>
        <li class="<%= sidebar_active_class('/deposits') %>">
          <%= link_to deposits_path do %>
            <i class="fa fa-bitcoin"></i> <span>Deposits</span>
          <% end %>
        </li>
      <% end %>
      <% if can? :manage, Currency %>
        <li class="<%= sidebar_active_class('/currencies') %>">
          <%= link_to currencies_path do %>
            <i class="fa fa-money"></i> <span>Currencies</span>
          <% end %>
        </li>
      <% end %>
      <% if can? :manage, Transaction %>
        <li class="<%= sidebar_active_class('/transactions') %>">
          <%= link_to transactions_path do %>
            <i class="fa fa-sign-out"></i> <span>Withdrawal Requests</span>
          <% end %>
        </li>
      <% elsif can? :index, Transaction %>
        <li class="<%= sidebar_active_class('/transactions') %>">
          <%= link_to transactions_path do %>
            <i class="fa fa-credit-card-alt"></i> <span>Wallet</span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </section>
</aside>

app/views/layouts/admin_lte_2.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhiltrickMiners AdminPanel</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body class="skin-green sidebar-mini <%= params[:controller].parameterize %> <%= action_name %>">
    <div class="wrapper">

      <%= render partial: 'layouts/admin_lte_2_header' %>

      <%= render partial: 'layouts/admin_lte_2_sidebar' %>

      <div class="content-wrapper">
        <section class="content-header">
          <h1>
            Philtrick
            <small>Admin Panel</small>
          </h1>
          <ol class="breadcrumb">
            <li><%= link_to authenticated_root_path do %><i class="fa fa-dashboard"></i> Home<% end %></li>
            <li class="active"> <%= breadcrumb_action_name %></li>
          </ol>
        </section>

        <section class="content">
          <% if notice %>
            <div class="alert alert-success alert-dismissable">
              <i class="fa fa-check"></i>
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
              <b><%= notice %></b>
            </div>
          <% end %>

          <% if alert %>
            <div class="alert alert-danger alert-dismissable">
              <i class="fa fa-ban"></i>
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
              <b><%= alert %></b>
            </div>
          <% end %>
          <%= yield %>
        </section>
      </div>

      <footer class="main-footer">
        <div class="pull-right hidden-xs">
        </div>
        <strong>Copyright © 2014 - 2018 <%= link_to "Philtrick Admin Panel", "#" %>.</strong> All rights reserved.
      </footer>

      <%= render partial: 'layouts/admin_lte_2_control_sidebar' %>

      <div class="control-sidebar-bg" style="position: fixed; height: auto;"></div>

    </div>
  </body>
</html>

app/views/layouts/admin_lte_2_login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>PhiltrickMiners AdminPanel | Log in</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

    <%= favicon_link_tag 'favicon.ico' %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class="login-page">
    <div class="login-box">
      <div class="login-logo">
        <%= link_to "#" do %><b>Philtrick</b>Admin Panel<% end %>
      </div>
      <div class="login-box-body">
        <% if alert %>
          <div class="alert alert-danger alert-dismissable">
            <i class="fa fa-ban"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <b><%= alert %></b>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdminPanelPhiltrick</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>